apiVersion: v1
kind: ConfigMap
metadata:
  name: sticked-words-config
data:
  ApplyMigrations: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: sticked-words-secret
type: Opaque
data:
  # "Data Source=/app/stickedwords.db"
  # DbConnectionString: RGF0YSBTb3VyY2U9L2FwcC9zdGlja2Vkd29yZHMuZGIK
  # "Host=pg-postgresql;Port=5432;Database=sticked-words;Username=app-user;Password=mypass"
  DbConnectionString: SG9zdD1wZy1wb3N0Z3Jlc3FsO1BvcnQ9NTQzMjtEYXRhYmFzZT1zdGlja2VkLXdvcmRzO1VzZXJuYW1lPWFwcC11c2VyO1Bhc3N3b3JkPW15cGFzcwo=
