@StickedWords.API_HostAddress = http://localhost:5206/api

GET {{StickedWords.API_HostAddress}}/flash-cards
Accept: application/json

###

GET {{StickedWords.API_HostAddress}}/flash-cards?skip=1&take=1&includeTotal=false
Accept: application/json

###

POST {{StickedWords.API_HostAddress}}/flash-cards
Accept: application/json
Content-Type: application/json

{
    "word": "Shcool",
    "translation": "Школа"
}