@StickedWords.API_HostAddress = https://localhost:7268

GET {{StickedWords.API_HostAddress}}/flash-cards
Accept: application/json

###

GET {{StickedWords.API_HostAddress}}/flash-cards?skip=1&take=1&includeTotal=false
Accept: application/json

###
