{
 "title": "StickedWords Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{}[2m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_received_total{}[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(http_request_duration_seconds_bucket[2m]))) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{code!~\"2.*\"}[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}