services:

  app:
    image: "molokmax/sticked-words:v0.1.6"
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings__StickedWordsDbContext=${CONNECTION_STRING}
      - DbProvider=PostgreSQL
      - ApplyMigrations=true
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
