name: Build Sticked-Words for self-contained deploy

on:
  push:
    branches: [ "main" ]

env:
  DOTNET_VERSION: '9.0'
  PROJECT_PATH: 'src/StickedWords.API'
  RUNTIME_IDENTIFIER: 'linux-arm'
  OUTPUT_DIR: 'publish'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Self-Contained
      run: |
        dotnet publish ${{ env.PROJECT_PATH }} \
          --configuration Release \
          --output ${{ env.OUTPUT_DIR }} \
          --runtime ${{ env.RUNTIME_IDENTIFIER }} \
          --self-contained true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sticked-words-${{ env.RUNTIME_IDENTIFIER }}
        path: ${{ env.OUTPUT_DIR }}/