name: Build Sticked-Words for self-contained deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0'
  NODE_VERSION: '22.14'
  API_PROJECT_PATH: 'src/StickedWords.API'
  UI_PROJECT_PATH: 'src/StickedWords.UI'
  RUNTIME_IDENTIFIER: 'linux-arm'
  OUTPUT_DIR: 'publish'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.UI_PROJECT_PATH }}/package-lock.json

    - name: Build UI
      working-directory: ${{ env.UI_PROJECT_PATH }}
      run: |
        npm install
        npm run build

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Self-Contained
      run: |
        dotnet publish ${{ env.API_PROJECT_PATH }} \
          --configuration Release \
          --output ${{ env.OUTPUT_DIR }} \
          --runtime ${{ env.RUNTIME_IDENTIFIER }} \
          --self-contained true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sticked-words-${{ env.RUNTIME_IDENTIFIER }}
        path: ${{ env.OUTPUT_DIR }}/