name: Build app for self-contained deploy

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '10.0'
  NODE_VERSION: '25'
  API_PROJECT_PATH: 'src/StickedWords.API'
  UI_PROJECT_PATH: 'src/StickedWords.UI.React'
  OUTPUT_DIR: 'publish'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [linux-arm, linux-x64]
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.UI_PROJECT_PATH }}/package-lock.json

    - name: Build UI
      working-directory: ${{ env.UI_PROJECT_PATH }}
      run: |
        npm install
        npm run build

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish Self-Contained
      run: |
        dotnet publish ${{ env.API_PROJECT_PATH }} \
          --configuration Release \
          --output ${{ env.OUTPUT_DIR }} \
          --runtime ${{ matrix.runtime }} \
          --self-contained true

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sticked-words-${{ matrix.runtime }}
        path: ${{ env.OUTPUT_DIR }}/